<?php

/**
 * Implements hook_menu().
 */
function rmh_country_flag_menu() {
  $items['admin/config/system/country_flag'] = array(
    'title' => 'List country flag',
    'page callback' => 'rmh_country_flag_page',
    'page arguments' => array('rmh_country_flag_admin_settings'),
    'access arguments' => array('administer content'),
    'file' => 'rmh_country_flag.admin.inc'
  );

  $items['admin/config/system/country_flag/add-new'] = array(
    'title' => 'Add country flag',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rmh_country_flag_add_form'),
    'access arguments' => array('administer content'),
    'file' => 'rmh_country_flag.admin.inc'
  );

  $items['admin/config/system/country_flag/%/delete'] = array(
    'title' => 'Delete Country Flag',
    'page callback' => '_rmh_country_list_delete',
    'page arguments' => array(4),
    'access arguments' => array('access content'),
    'file' => 'rmh_country_flag.admin.inc'
  );

  $items['admin/config/system/country_flag/%/edit'] = array(
    'title' => 'Edit Country Flag',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rmh_country_flag_edit_form', 4),
    'access arguments' => array('administer content'),
    'file' => 'rmh_country_flag.admin.inc'
  );

  return $items;
}

/**
 * Render flag output.
 */
function rmh_country_flag_render() {

  $results = db_select('rmh_country_flag', 'cf')
    ->fields('cf')
    ->orderBy('weight', 'ASC')
    ->execute()->fetchAll();

  $items = array();

  foreach ($results as $k => $item) {
    $items[$k]['image'] = file_create_url(file_load($item->fid)->uri);
    $items[$k]['url'] = $item->country_url;
  }

  return $items;
}

/**
 * Insert flags array in variables.
 */
function rmh_country_flag_preprocess_page(&$variables) {

  $variables['flags'] = rmh_country_flag_render();

}